### ISSUE TITLE
Next.js\TypeError: Cannot read property 'Embed' of undefined

### ISSUE THREAD

**Issue by ghost** [moonstar-x/react-twitch-embed#27]
Lovely package, thanks for dealing with all the crap for us, unfortunately, the `TwitchEmbed` doesn't work at all.

I'm running on the latest version of `next.js`, on **localhost**. I tested chat and the others, they work. 

I don't see the request for twitch's JS files at all. I am using server-side rendering, since, well, it is, after all, a Next.js app, however, this component isn't SSR, or so I think. 

This component loads on every page, very, very early on. Here's the dump [, included as an image if you prefer that:](https://i.imgur.com/IgcUGSK.png)

```
Unhandled Runtime Error
TypeError: Cannot read property 'Embed' of undefined

Call Stack
TwitchEmbed._createEmbed
node_modules\react-twitch-embed\dist\index.es.js (220:0)

TwitchEmbed.componentDidUpdate
/_next/static/chunks/pages/_app.js (46980:21)

commitLifeCycles
node_modules\react-dom\cjs\react-dom.development.js (19835:0)

commitLayoutEffects
/_next/static/chunks/main.js (43099:7)

HTMLUnknownElement.callCallback
node_modules\react-dom\cjs\react-dom.development.js (188:0)

Object.invokeGuardedCallbackDev
/_next/static/chunks/main.js (20533:16)

invokeGuardedCallback
node_modules\react-dom\cjs\react-dom.development.js (292:0)

commitRootImpl
/_next/static/chunks/main.js (42837:9)

unstable_runWithPriority
node_modules\scheduler\cjs\scheduler.development.js (653:0)

runWithPriority$1
/_next/static/chunks/main.js (31335:10)

commitRoot
node_modules\react-dom\cjs\react-dom.development.js (22381:0)

finishSyncRender
/_next/static/chunks/main.js (42103:3)

performSyncWorkOnRoot
node_modules\react-dom\cjs\react-dom.development.js (21793:0)

<unknown>
/_next/static/chunks/main.js (31385:24)

unstable_runWithPriority
node_modules\scheduler\cjs\scheduler.development.js (653:0)

runWithPriority$1
/_next/static/chunks/main.js (31335:10)

flushSyncCallbackQueueImpl
node_modules\react-dom\cjs\react-dom.development.js (11084:0)

flushSyncCallbackQueue
/_next/static/chunks/main.js (31368:3)

flushPassiveEffectsImpl
node_modules\react-dom\cjs\react-dom.development.js (22883:0)

unstable_runWithPriority
/_next/static/chunks/main.js (49289:12)

runWithPriority$1
node_modules\react-dom\cjs\react-dom.development.js (11039:0)

flushPassiveEffects
/_next/static/chunks/main.js (43116:12)

<unknown>
node_modules\react-dom\cjs\react-dom.development.js (22699:0)

workLoop
/_next/static/chunks/main.js (49233:34)

flushWork
node_modules\scheduler\cjs\scheduler.development.js (552:0)

MessagePort.performWorkUntilDeadline
/_next/static/chunks/main.js (48800:27)
```
I can see that it's calling `unknownHTMLElement` which makes me think it failed to load properly at all.

**Comment by moonstar-x** [comment]
Hey there, sorry for any inconvenience this may be causing. I'm curious about how you're rendering the `TwitchEmbed` component. How are you updating the props? Are the props changing immediately? Which props are changing? I'm seeing the error comes from the `componentDidUpdate()` which handles the manual embed recreation, so I imagine that the component has certainly been mounted previously (where the initial embed script download occurs).

I'm trying to reproduce this on next.js to no avail.

Another option (which should not be taken as an actual solution) would be to use dynamic imports if your project's scope allows for this. This means that `TwitchEmbed` would be all client-side rendered. You could import `TwitchEmbed` as such:

```js
import dynamic from 'next/dynamic';

const DynamicTwitchEmbed = dynamic(() => {
  return import('react-twitch-embed').then((mod) => mod.TwitchEmbed));
}, { ssr: false });
```

And use the component with:

```jsx
<DynamicTwitchEmbed channel="channel" />
```

**Comment by glottonous** [comment]
Sorry for the late reply, you're right, dynamic imports solve this, but the questions you asked (due to my lack of experience) didn't help me identify the issue per-se. **I understand that it's an order issue** but then, how do you make a component wait for an outside script to load? The `window.Twitch` object just simply doesn't exist and when the component gets mounted or even rendered, it still might not be there, causing issues.

**Comment by moonstar-x** [comment]
I'm not 100% if it's an order issue. In theory the component does know when the script finishes downloading and it is then that it creates the embed. I was asking you if you were updating your component before the embed was created. I was trying to reproduce this in next.js but I don't get any errors.

**Comment by moonstar-x** [comment]
Hi there, sorry for the long hiatus.

I'm gonna close this issue due to inactivity. However, I have just updated this package to version `3.0.1` with #37.

Any reference to `window` or `document` have been moved to `useEffect()` which should be executed in the client for SSR apps.

If you feel this was a mistake, feel free to re-open this issue.

Thanks!
